### ISSUE TITLE
Kosovo (KX)

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [flyingcircusio/pycountry#70]
[Kosovo is recognised by 98 out of 193 (51%) of UN member states and the majority of the EU](https://en.wikipedia.org/wiki/International_recognition_of_Kosovo). In full understanding of the politically sensitive nature of this issue, may I nonetheless suggest that we integrate Kosovo into `pycountry`? We can put a disclaimer on that `pycountry`'s 'recognition' of a country is not a political statement one way or the other (an example is [this disclaimer by the WMO](https://public.wmo.int/en/disclaimer)).

**Comment by lizkrznarich** [comment]
The correct code alpha-2 code is XK as in https://github.com/flyingcircusio/pycountry/pull/60/files, but, regardless, I'm curious if there are any plans to support Kosovo in pycountry. I'm part of a team that runs an open organization identifier service for research institutions ([Research Organization Registry](https://ror.org/)) and we are running into issues using pycountry in our search API because of records with XK in the country field.

**Comment by QuLogic** [comment]
See the note in the README:

> # Data update policy
>
> No changes to the data will be accepted into pycountry. This is a pure wrapper around the ISO standard using the pkg-isocodes database from Debian as is. If you need changes to the political situation in the world, please talk to the ISO or Debian people, not me.

You should report this to https://salsa.debian.org/iso-codes-team/iso-codes if you want updates to the data.

**Comment by ctheune** [comment]
Thanks @QuLogic for stepping in!
