### ISSUE TITLE
Publish wheels

### ISSUE THREAD

**Issue by vsalvino** [flyingcircusio/pycountry#87]
Would you be able to publish wheels (.whl) in addition to the source distributions? One advantage to wheels from the python infrastructure standpoint is they install much faster as PyPI is able to pre-resolve the dependencies. And if your package is "pure" python (no C extensions) then building a wheel is very simple.

The command to build both source distribution and wheel is:
```
$ pip install wheel
$ python setup.py sdist bdist_wheel
```
Then upload both as usual to PyPI. I would be happy to help if needed, just let me know!

For more into see: https://pythonwheels.com/

**Comment by six8** [comment]
I just ran into this as well. The previous version I used had a wheel https://pypi.org/project/pycountry/18.5.26/#files

Later versions do not.

**Comment by bastimeyer** [comment]
@ctheune could you please publish wheels for pycountry (again)? It is the only dependency of our project which is not distributed as a wheel on pypi, and this is causing some headaches for me.

The reason why I'm asking is that I need to manually build dependency lockfiles via pip for packaging our project for other specific platforms. Since the proposed `pip resolve` command has not been implemented yet and since I can't generate the lockfiles in a python environment that is run natively on the target platforms, the only way how this can be done is downloading packages from pypi via `pip download` while setting the `--implementation`, `--platform`, `--python-version` and `--abi` parameters, installing the downloaded packages and listing them via `pip list`. The `pip download` command however requires `--only-binary=:all:` to be set as well when any of the parameters I just mentioned are set, and this obviously excludes recent builds of pycountry as there's no wheel available. The last pycountry release which was published as a wheel is 18.x, so this ancient version matches the `--only-binary=:all:` constraint, which is not particularly great, and I have to add a pycountry exception to my lockfile generator script and build a pycountry wheel locally from the most recent version.

I would really appreciate it if a `py3-none-any` wheel could be published in addition to the srcdist. Thanks.

I would've opened a pull request for an upgrade of any existing CI configurations that publish to pypi, but there don't seem to be any, so I guess this is done manually right now.

**Comment by PeterJCLaw** [comment]
@ctheune just wondering if there's anything that we could do to help with this?

**Comment by ctheune** [comment]
We should be publishing wheels with the next release. I switched to poetry and I saw it build wheels in tests already.

**Comment by allanlewis** [comment]
There are no wheels for the latest version at time of writing, 22.3.5: https://pypi.org/project/pycountry/22.3.5/#files

I think this issue should be re-opened.

**Comment by zware** [comment]
No need to reopen, the next release will have wheels.  There just hasn't been one recently.
